/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.VendaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Venda;

/**
 *
 * @author pc
 */
public class TelaHistoricoVenda extends javax.swing.JPanel {

    /**
     * Creates new form TelaHistoricoVendas
     */
    public TelaHistoricoVenda() {
        initComponents();
    }

    public DefaultTableModel gerarModeloVenda(List<Venda> vendas) {
    String[] colunas = {"ID", "Cliente","Data", "Itens", "Total"};
    DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

    for (Venda v : vendas) {
        Object[] linha = {
            v.getId(),
            v.getCliente().getNome(),
            v.getDataVenda(),
            v.getItens(),
            v.getValorTotal()
        };
        modelo.addRow(linha);
    }

    return modelo;
    }
    VendaDAO dao = new VendaDAO();
    List<Venda> vendas = dao.listarVendasCompletas();

    DefaultTableModel modelo = gerarModeloVenda(vendas);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaHistorico = new javax.swing.JTable();

        TabelaHistorico.setModel(modelo);
        jScrollPane2.setViewportView(TabelaHistorico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaHistorico;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
